main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
    # this root route will display the home page
    path('', views.home, name='home'),
    # this route will display the about page
    path('about/', views.about, name='about'),
    path('care/', views.care_tips, name='tips'),
    path('plants/', views.plants_index, name='index'),
    path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/<int:plant_id/add_plant_care/', views.add_plant_care, name='add_care'),
    path('plants/create/', views.PlantCreate.as_view(), name='create'),
    path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='update'),
    path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='delete'),
    path('quiz/', views.quiz, name='quiz'),
    path('submit_quiz/', views.SubmitQuiz.as_view(), name='submit_quiz'),

]

plant_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # routes from main_app included here
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

#Tuple of 2-tuples - options for drop down menus
TYPES = (
    ('W', 'Watered'),
    ('F', 'Fertilized'),
    ('P', 'Pruned'),
    ('R', 'Repotted'),
    ('PC', 'Pest Control'),
)

# Create your models here.
class Plant(models.Model):
    name = models.TextField()
    species = models.TextField()
    botanical_name = models.TextField()
    notes = models.TextField()

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})

class Plant_Care(models.Model):
    date = models.DateField('date')
    type = models.CharField(
        max_length=2,
        choices=TYPES,
        default=TYPES[0][0]
    )
    # Create a plant_id foreign key
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.get_type_display()} on {self.date}'

class Quiz(models.Model):
    question1 = models.TextField()
    question2 = models.TextField()
    question3 = models.TextField()
    question4 = models.TextField()

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('detail', kwargs={'quiz_id': self.id})

class QuizSubmit(models.Model):
    HARDINESS_ZONE_CHOICES = [(str(i), str(i)) for i in range(1, 13)]
    SUN_CHOICES = [
        ('full_sun', 'Full Sun'),
        ('partial_sun', 'Partial Sun'),
        ('partial_shade', 'Partial Shade'),
        ('full_shade', 'Full Shade'),
    ]
    WATER_FREQUENCY_CHOICES = [
        ('frequent', 'Frequent'),
        ('average', 'Average'),
        ('minimal', 'Minimal'),
    ]
    MAINTENANCE_LEVEL_CHOICES = [
        ('low', 'Low'),
        ('moderate', 'Moderate'),
        ('high', 'High'),
    ]

main_app/forms.py
from django.forms import ModelForm
from .models import Plant_Care

class Plant_CareForm(ModelForm):
    class Meta:
        model = Plant_Care
        fields = ['date', 'type']

main_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Plant, Quiz
from .forms import Plant_CareForm

# Create your views here.

# Define the home view
def home(request):
    return render(request, 'home.html') # The .html file extension renders the home page template
# Define the about view
def about(request):
    return render(request, 'about.html')
# Define the quiz view
def quiz(request):
    return render(request, 'quiz/quiz.html', {
        'quiz': quiz
    })
# Define the plants view
def plants_index(request):
    plants = Plant.objects.all()
    return render(request, 'plants/index.html', {
        'plants': plants
    })
# Define the care view
def care_tips(request):
    return render(request, 'tips.html')
# Define the plants_detail view
def plants_detail(request, plant_id):
    plant = Plant.objects.get(id=plant_id)
    # instantiate the Plant_CareForm to be rendered in the template
    plant_care_form = Plant_CareForm()
    return render(request, 'plants/detail.html', {
        'plant': plant, 'plant_care_form': plant_care_form
    })

# Define the Plant views Create, Update, and Delete
class PlantCreate(CreateView):
    model = Plant
    fields = '__all__'
    success_url = '/plants/' # Redirect to the plants index page after creating a new plant

class PlantUpdate(UpdateView):
    model = Plant
    fields = ['species', 'botanical_name', 'notes']

class PlantDelete(DeleteView):
    model = Plant
    success_url = '/plants/' # Redirect to the plants index page after deleting a plant

# Define the submit_quiz view
class SubmitQuiz(CreateView):
    model = Quiz
    fields = '__all__'
    success_url = '/quiz/' # Redirect to the quiz page after submitting the quiz

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

    <center> <h2>WELCOME TO PLANT-LIFE</h2> </center>
    <center> <p>WHERE NATURE MEETS TECHNOLOGY</p> </center>
    <hr>
    <h4>ABOUT US</h4>
    <p>Our platform is dedicated to helping plant enthusiasts, gardeners, nature lovers, and even beginners discover the perfect foliage for their environment. Whether you're looking to create a vibrant garden, green up your indoor space, or simply learn more about the plants around you and their benefits, Plant-Life is here to guide you.</p>

    <p>Plant-Life utilizes cutting-edge technology to provide personalized plant recommendations based on your location, climate, and specific goals. By considering factors such as geography, temperature zones, and local climate conditions, we aim to empower users to make informed decisions about their plant choices without all the overwhelming guesswork.</p>

    <p>Join the Plant-Life community to embark on a journey to explore the wonderful world of plants, and let's grow together!</p>

    <h4>THE CREATORS</h4>
    <p>Founded by a team of beginners, we wanted to make the process of selecting and caring for plants more accessible and enjoyable for everyone. Our team is dedicated to providing a seamless and user-friendly experience for all users, regardless of their level of expertise.</p>
    <li>Hetal Ajmeri - UX/UI Designer</li>
    <li>Krystalin Castillo - Software Engineer</li>
    <li>Kim Ellison - UX/UI Designer</li>
    <li>Vijay Ravuri - Data Scientist</li>
    <br>
    <br>
    <center> <h5>HAPPY PLANTING!</h5> </center>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Plant-Life</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Plant-Life</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">ABOUT</a></li>
          <li><a href="{% url 'quiz' %}">TAKE THE QUIZ!</a></li>
          <!-- <li><a href="{% url 'create' %}">ADD A PLANT</a></li> (link added directly to index page)-->
          <li><a href="{% url 'index' %}">MY PLANTS</a></li>
          <li><a href="{% url 'tips' %}">CARE TIPS</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="center">All Rights Reserved &copy; 2024 Plant-Life &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/care.html
{% extends 'base.html' %}

{% block content %}

    <center> <h2>WELCOME TO YOUR BEGINNERS GARDEN!</h2> </center>
    <center> <p>PLANTING TIPS FOR OVERWHELMED GARDNERS</p> </center>
    <hr>
    <p>Are you a budding gardener, eager to transform your outdoor space into a lush haven of greenery? Or perhaps you've been eyeing that sunny windowsill, dreaming of homegrown herbs and veggies? Fear not! Our planting tips page is here to guide you through the exciting journey of gardening, one step at a time.</p>

    <h5>1. Essential Gardening Basics</h5>
    <h6>Selecting a Site</h6>
    <li>Sunlight Matters: Most vegetables thrive in full sun, which means they need 6 to 8 hours of direct sunlight daily. Leafy greens can tolerate partial shade, but sun-loving plants like tomatoes and peppers require maximum light exposure.</li>

    <li>Choose Wisely: Pick a spot that receives ample sunlight and has well-draining soil. Avoid areas with heavy foot traffic or where water tends to pool.</li>

    <h6>Soil Preparation</h6>
    <p>Healthy Soil, Happy Plants: Nutrient-rich soil is the foundation of a successful garden. Here’s how to prepare it:
        <li>Test the Soil: Use a soil test kit to check the pH levels and nutrient content of your soil.</li>
        <li>Amend with Organic Matter: Add compost, well-rotted manure, or other organic materials to improve soil structure and fertility.</li>
    </p>
    <h6>Plot Size</h6>
    <li>Start Small: It’s tempting to go all out, but as a beginner, it’s better to start with a manageable plot. A 4x4-foot raised bed or a few containers are perfect.</li>
    <li>Quality Over Quantity: Focus on a few crops you love and know you’ll eat. Don’t overwhelm yourself with too many varieties.</li>

    <h5>2. Vegetable Selection and Planting</h5>
    <h6>Choosing Your Vegetables</h6>
    <p>Beginner-Friendly Veggies:</p>
    <li>Tomatoes: Easy to grow and rewarding. Choose determinate varieties for compact spaces.</li>
    <li>Lettuce: Fast-growing and perfect for salads.</li>
    <li>Carrots: Sow directly in the soil—they don’t like transplanting.</li>
    <p>Companion Planting:</p>
    <li>Plant basil near tomatoes to enhance flavor and repel pests.</li>

    <h5>3. Troubleshooting and FAQs</h5>
    <h6>Common Challenges and Solutions</h6>
    <li>Pests:</li>
    <p>- Identify common garden pests (aphids, slugs, etc.).</p>
    <p>- Use organic pest control methods (neem oil, companion planting).</p>
    <li>Overwatering:</li>
    <p>- Learn to gauge soil moisture.</p>
    <p>- Water deeply but less frequently.</p>
    <li>Yellowing Leaves:</li>
    <p>- Could indicate nutrient deficiencies (nitrogen, iron).</p>
    <p>- Adjust fertilization accordingly.</p>
    <br>
    <br>
    <center> <h5>REMEMBER, GARDENING IS A JOURNEY, NOT A DESTINATION.</h5> </center>
    <center> <h5>HAPPY PLANTING!</h5> </center>

{% endblock %}

main_app/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plant-Life</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Plant-Life</a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">ABOUT</a></li>
                    <li><a href="/quiz">TAKE THE QUIZ!</a></li>
                    <li><a href="/plants">MY PLANTS</a></li>
                    <li><a href="/care">CARE TIPS</a></li>
                    </ul>
            </div>
        </nav>
    </header>
   <center> 
        <div class="title-box">
            <center> <h1>Plant-Life</h1> </center>
        </div> 
    </center>
    <footer class="page-footer">
        <div class="center">All Rights Reserved &copy; 2024 Plant-Life &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/main_app/add_plant.html
{% extends 'base.html' %}

{% block content %}
<style>
  form, form * {
    color: black;
  }
</style>
  <center> <h2>ADD A PLANT</h2> </center>
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <center> <input type="submit" value="Add!" class="btn, green-color"> </center>
  </form>
{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
<!-- Template no longer needed with pop-up box in javascript code being implemented. -->

<!-- {% extends 'base.html' %}

{% block content %}

  <center> <h3>Are you sure you want to delete this plant?</h3> </center>

  <center> <h4><span class="green-text">{{ plant.name }}</span></h4> </center>

  <form action="" method="POST">
    {% csrf_token %}
    <center> <input type="submit" value="YES - DELETE!"> </center>
    <center> <a href="{% url 'detail' plant.id %}" class="cancel-link">CANCEL</a> </center>
  </form>

{% endblock %} -->

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}

{% block content %}
<style>
  form, form * {
    color: black;
  }
</style>

{% if object %}
    <h2>EDIT <span class="green-text">{{object.name}}</span></h2>
  {% else %}
    <center> <h2>ADD A PLANT</h2> </center>
  {% endif %}

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>

    {% if object %}
      <center> <input type="submit" value="UPDATE"> </center>
      <center> <a href="{% url 'detail' plant.id %}" class="cancel-link">CANCEL</a> </center>
    {% else %}
      <center> <input type="submit" value="ADD +"> </center>
      <center> <a href="{% url 'index' %}" class="cancel-link">CANCEL</a> </center>
    {% endif %}
    
  </form>

{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

  <center> <h2>MY PLANT DETAILS</h2> </center>
  <hr>

  <!-- Plant Details -->
  <!-- <div class="row">
    <div class="col s6"> -->
      <div class="card">
        <div class="card-content">
          <h5> <span class="card-title, green-text"><strong>{{ plant.name }}</strong></span> </h5>
          <p><strong>Species:</strong> {{ plant.species }}</p>
          <p><strong>Botanical Name:</strong> {{ plant.botanical_name }}</p>
          <p><strong>Notes:</strong> {{ plant.notes|linebreaks }}</p>
        </div>
        <div class="card-action">
          <center>
            <a href ="{% url 'update' plant.id %}" class="green-text">EDIT</a>
            <!-- <a href="{% url 'delete' plant.id %}" class="green-text">DELETE</a> -->
            <!-- The link above ^ is the old link needed to render the delete confirmation template. -->
            <!-- It is no longer needed since javascript is being used. The link below allows the box to populate and the # prevents the back end from trying to render a new page. -->
            <a href="#" id="delete" class="green-text">DELETE</a>
          </center>
        </div>

        <!-- Plant Care Schedule -->
        <!-- plant care form -->
        <form method="POST">
          {% csrf_token %}
          <!-- Render the inputs -->
          {{ plant_care_form.as_p }}
          <center> <input type="submit" class="btn" value="+"> </center>
        </form>
        <br>
        <table class="striped">
          <thead>
            <tr><th>Date</th><th>Care</th></tr>
          </thead>
          <tbody>
            {% for plant_care in plant.plant_care_set.all %}
              <tr>
                <td>{{plant_care.date}}</td>
                <td>{{plant_care.get_type_display}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>  
  </div>


  <!-- Delete confirm pop up box  -->
  <!-- (delete_confirm_form.html commented out) -->
  <!-- Django can't do a pop up box, front end task, javascript needs to be used with some CSS. -->
  <div id="deleteBox" class="box">
    <div class="box-content">
      <center>
        <h4>Are you sure you want to delete your <span class="green-text">{{ plant.name }}</span>?</h4>
      </center>
      <!-- form action is the delete url here as it tells the post request to trigger the delete. -->
      <form action="{% url 'delete' plant.id %}" method="POST">  
        {% csrf_token %}
        <center> <input type="submit" value="YES - DELETE!" class="delete"> </center>
        <center> <a href="{% url 'detail' plant.id %}" class="cancel-link">CANCEL</a> </center>
      </form>
    </div>
  </div>
  <!-- This javascript functions add an event listener that will tell the box what to do when the delete or cancel buttons are clicked. -->
  <script>
    document.getElementById('delete').onclick = function() {
    document.getElementById('deleteBox').style.display = 'block';
    }

    document.getElementById('cancel').onclick = function() {
    document.getElementById('deleteBox').style.display = 'none';
    }
  </script>

  <!-- Add plant care form -->
  <div id="addCare" class="">
    <script>
      // Date-picker
      const dateEl = document.getElementById('id_date');
      // M is Materialize's global variable
      M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
      });

      // Care-type selector
      const selectEl = document.getElementById('id_type');
      M.FormSelect.init(selectEl);
    </script>
  </div>
  <br>
  <br>
  <!-- 'Back to Plants' link -->
  <center><a href="{% url 'index' %}" class="back-link">BACK TO MY PLANTS</a></center>

{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}
<style>
  form, form * {
    color: black;
  }
</style>

<center> <h2>MY PLANTS</h2> </center>
<hr>
{% for plant in plants %}
  <div class="card">
    <a href="/plants/{{ plant.id }}">
      <div class="card-content">
        <h6> <span class="card-title, green-text"><strong>{{ plant.name }}</strong></span> </h6>
        <p class="black-text"> {{ plant.botanical_name }} </p>
      </div>
    </a>
  </div>
  {% endfor %}
  
  <center> <a href="{% url 'create' %}" class="btn">ADD A PLANT</a> </center>

{% endblock %}

main_app/templates/quiz/quiz.html
{% extends 'base.html' %}
{% block content %}
<style>
  form, form * {
    color: black;
  }
</style>

<center> <h2>WHICH PLANTS ARE BEST?</h2> </center>
<center> <p>TAKE THE QUIZ!</p> </center>
<hr>
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ quiz }}</span>
        <form action="/submit_quiz/" method="post">
            {% csrf_token %}
            <p>
                <label for="question1">1: What is your Hardiness Zone?
                    <a href="https://planthardiness.ars.usda.gov" target="_blank">(Check here)</a>
                </label>
                <input type="text" id="question1" name="question1">
                <br>
                <br>
                <label for="question2">2: How much sun does your gardening space have?
                    <br>
                    Full Sun: 6-8 hours per day, occurs mostly between 10 a.m. and 4 p.m. on most days.
                    <br>
                    Partial Sun: 4-6 hours per day, not continuous: morning sun, followed by shade midday, and then more sun in the afternoon.
                    <br>
                    Partial Shade: 2-4 hours per day, typically in the morning only.
                    <br>
                    Full Shade: Less than 2 hours per day, typically in the morning only.
                </label>
                <input type="text" id="question2" name="question2">
                <br>
                <br>
                <label for="question3">3: How often are you able to water your plant(s)?
                    <br>
                    Frequent: Daily
                    <br>
                    Average: Once every few days
                    <br>
                    Minimal: Once a week
                </label>
                <input type="text" id="question3" name="question3">
                <br>
                <br>
                <label for="question4">4: What level of plant maintenance are you comfortable caring for?
                    <br>
                    Low: I want a plant that requires minimal care.
                    <br>
                    Moderate: I want a plant that requires some care.
                    <br>
                    High: I want a plant that requires a lot of care.
                </label>
                <input type="text" id="question4" name="question4">
            </p>
            <br>
            <center> <input type="submit" value="SUBMIT"> </center>
        </form>
    </div>
  </div>

{% endblock %}

main_app/templates/tips.html
{% extends 'base.html' %}

{% block content %}

    <center> <h2>WELCOME TO YOUR BEGINNERS GARDEN!</h2> </center>
    <center> <p>PLANTING TIPS FOR OVERWHELMED GARDNERS</p> </center>
    <hr>
    <p>Are you a budding gardener, eager to transform your outdoor space into a lush haven of greenery? Or perhaps you've been eyeing that sunny windowsill, dreaming of homegrown herbs and veggies? Fear not! Our planting tips page is here to guide you through the exciting journey of gardening, one step at a time.</p>

    <h5>1. Essential Gardening Basics</h5>
    <h6>Selecting a Site</h6>
    <li>Sunlight Matters: Most vegetables thrive in full sun, which means they need 6 to 8 hours of direct sunlight daily. Leafy greens can tolerate partial shade, but sun-loving plants like tomatoes and peppers require maximum light exposure.</li>

    <li>Choose Wisely: Pick a spot that receives ample sunlight and has well-draining soil. Avoid areas with heavy foot traffic or where water tends to pool.</li>

    <h6>Soil Preparation</h6>
    <p>Healthy Soil, Happy Plants: Nutrient-rich soil is the foundation of a successful garden. Here’s how to prepare it:
        <li>Test the Soil: Use a soil test kit to check the pH levels and nutrient content of your soil.</li>
        <li>Amend with Organic Matter: Add compost, well-rotted manure, or other organic materials to improve soil structure and fertility.</li>
    </p>
    <h6>Plot Size</h6>
    <li>Start Small: It’s tempting to go all out, but as a beginner, it’s better to start with a manageable plot. A 4x4-foot raised bed or a few containers are perfect.</li>
    <li>Quality Over Quantity: Focus on a few crops you love and know you’ll eat. Don’t overwhelm yourself with too many varieties.</li>

    <h5>2. Vegetable Selection and Planting</h5>
    <h6>Choosing Your Vegetables</h6>
    <p>Beginner-Friendly Veggies:</p>
    <li>Tomatoes: Easy to grow and rewarding. Choose determinate varieties for compact spaces.</li>
    <li>Lettuce: Fast-growing and perfect for salads.</li>
    <li>Carrots: Sow directly in the soil—they don’t like transplanting.</li>
    <p>Companion Planting:</p>
    <li>Plant basil near tomatoes to enhance flavor and repel pests.</li>

    <h5>3. Troubleshooting and FAQs</h5>
    <h6>Common Challenges and Solutions</h6>
    <li>Pests:</li>
    <p>- Identify common garden pests (aphids, slugs, etc.).</p>
    <p>- Use organic pest control methods (neem oil, companion planting).</p>
    <li>Overwatering:</li>
    <p>- Learn to gauge soil moisture.</p>
    <p>- Water deeply but less frequently.</p>
    <li>Yellowing Leaves:</li>
    <p>- Could indicate nutrient deficiencies (nitrogen, iron).</p>
    <p>- Adjust fertilization accordingly.</p>
    <br>
    <br>
    <center> <h5>REMEMBER, GARDENING IS A JOURNEY, NOT A DESTINATION.</h5> </center>
    <center> <h5>HAPPY PLANTING!</h5> </center>

{% endblock %}